# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# TaskTracker installs the task-tracker command-line binary.
class TaskTracker < Formula
  desc "PostgreSQL-backed task tracker with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/task-tracker"
  version "0.0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-d9fa57e_darwin_arm64.tar.gz"
      sha256 "71c230929e586f1935dd3be47d8b8f3f929b5e685c3563947356e072925f952a"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-d9fa57e_darwin_amd64.tar.gz"
      sha256 "270efff185ca9c6a992ed82e0792ff6591790bfcef72f03e15ca1b9930437892"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-d9fa57e_linux_arm64.tar.gz"
      sha256 "5af58ae9cebe7a1967a28d2bc929adb6d35c873f2789b9d0f81f188a1acffcf2"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-d9fa57e_linux_amd64.tar.gz"
      sha256 "9fbffa4bbe477918d6471a63b80d6682ef72ed661c2157e9a8242f5f03ad9d3f"
    end
  end

  def install
    bin.install "task-tracker"
  end

  test do
    assert_equal "edge-SNAPSHOT-d9fa57e\n", shell_output("#{bin}/task-tracker version")
  end
end
