# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# TaskTracker installs the task-tracker command-line binary.
class TaskTracker < Formula
  desc "PostgreSQL-backed task tracker with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/task-tracker"
  version "0.0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-514c968_darwin_arm64.tar.gz"
      sha256 "baa9fd1be22419ec182a076c840812944c1555e67ceac5987fccbae24159f918"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-514c968_darwin_amd64.tar.gz"
      sha256 "c631f6eb9d400421b1caf5b5e5eb35c0fee4faeea24feed89863b5b55d90aef5"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-514c968_linux_arm64.tar.gz"
      sha256 "372c0c012708babc50f4ed46d942aa9c41b04c102fc8a07343f3729a3cfa465b"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-514c968_linux_amd64.tar.gz"
      sha256 "481fdd5e17f81fb5c3b0dce514cf34e3dec238166753761aa3bf810da0b3ef3b"
    end
  end

  def install
    bin.install "task-tracker"
  end

  test do
    assert_equal "edge-SNAPSHOT-514c968\n", shell_output("#{bin}/task-tracker version")
  end
end
