# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/tasks"
  version "0.0.0.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-ae6e890_darwin_arm64.tar.gz"
      sha256 "0494bee8a2ac8e37daae755c8a58a03a64b89aadee463c37ab43adafbfaa54fb"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-ae6e890_darwin_amd64.tar.gz"
      sha256 "a16f81e0d5744d962c7b90211a84d8627206e2cca60878eaed0b0ef4de91608a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-ae6e890_linux_arm64.tar.gz"
      sha256 "c4b2199ccf8207b7a58af0a1bb9e6b4f14e747618925536b6ef9742b322388de"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-ae6e890_linux_amd64.tar.gz"
      sha256 "a686510ce2aab84f4ab64993df18f40ad4ba5cbe046666a01bfd41888d1baa61"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "edge-SNAPSHOT-ae6e890\n", shell_output("#{bin}/tasks version")
  end
end
