# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/tasks"
  version "0.0.0.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-70b1086_darwin_arm64.tar.gz"
      sha256 "5aa9410a5ee364f548f1a446eafacbeb84d275f073a3e71e29303545b4f4c187"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-70b1086_darwin_amd64.tar.gz"
      sha256 "17ba25ed0b3bedf8da0879cfebe4819eee207a5a91469fed8b53d87889c6395a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-70b1086_linux_arm64.tar.gz"
      sha256 "a3dfb6efc9ec166caedaf1ed244ece315f1901a60c157311ee502fba59560977"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-70b1086_linux_amd64.tar.gz"
      sha256 "b2faef0149063fe8a5c4be4d6f23b92d0a99854dff55514f8a6b2d5155ab6fbf"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "edge-SNAPSHOT-70b1086\n", shell_output("#{bin}/tasks version")
  end
end
