# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# Tasks installs the tasks command-line binary.
class Tasks < Formula
  desc "PostgreSQL-backed task management with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/tasks"
  version "0.0.0.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-bb7e811_darwin_arm64.tar.gz"
      sha256 "cc649eb105f4041553c44a89ffe042720799a934a02f28636d3d3859985b4fad"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-bb7e811_darwin_amd64.tar.gz"
      sha256 "0b57837bf2477798f2a0d194db78de21774afc7fe8e80a1840e18a646924e139"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-bb7e811_linux_arm64.tar.gz"
      sha256 "fee2b42944fc52b2bcfe585f3e414e14f3a25bfd6aecfceb1ba5ebab7162930a"
    else
      url "https://github.com/zachlatta/tasks/releases/download/edge/tasks_edge-SNAPSHOT-bb7e811_linux_amd64.tar.gz"
      sha256 "0c4aaacb02c4e475659bd18e5160befb774343865a3aed8dcd4482d8ae540398"
    end
  end

  def install
    bin.install "tasks"
  end

  test do
    assert_equal "edge-SNAPSHOT-bb7e811\n", shell_output("#{bin}/tasks version")
  end
end
