# typed: false
# frozen_string_literal: true

# Code generated by cmd/update-homebrew-formula. DO NOT EDIT.

# TaskTracker installs the task-tracker command-line binary.
class TaskTracker < Formula
  desc "PostgreSQL-backed task tracker with CLI, web, and MCP interfaces"
  homepage "https://github.com/zachlatta/task-tracker"
  version "0.0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-987c594_darwin_arm64.tar.gz"
      sha256 "7ba783f068afcc6b116881a5c6c49ac0d00917e9d868b5a10d9a5884bfabed9d"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-987c594_darwin_amd64.tar.gz"
      sha256 "6f61b3758885c91595aa7d567c61e89e2917f3257282c14d1b01fdd04eeab520"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-987c594_linux_arm64.tar.gz"
      sha256 "386867aa66c99139e35d49205573bcf33407bafa534ae721ec3bd2e0ef75e01a"
    else
      url "https://github.com/zachlatta/task-tracker/releases/download/edge/task-tracker_edge-SNAPSHOT-987c594_linux_amd64.tar.gz"
      sha256 "c51c33236d614598e35d66b1bb6aafc80c42d16ea1e4e7fc45b20ee64a5c8518"
    end
  end

  def install
    bin.install "task-tracker"
  end

  test do
    assert_equal "edge-SNAPSHOT-987c594\n", shell_output("#{bin}/task-tracker version")
  end
end
